name: Publish and Create GitHub Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: publish JARs
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            Mavenm Spring dependency:

            ```xml
            <dependency>
              <groupId>at.jkvn.dtosimplify</groupId>
              <artifactId>dto-simplify-spring</artifactId>
              <version>${{ github.ref_name }}</version>
            </dependency>
            ```
            
            Mavenm Quarkus dependency:
            **In Progress**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}