name: Publish and Create GitHub Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # wichtig fürs Release
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and publish JARs
        run: ./gradlew publish build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find all JAR files
        run: |
          mkdir artifacts
          find . -name "*.jar" -not -path "*/build/tmp/*" -exec cp {} artifacts/ \;

      - name: Create GitHub Release and upload JARs
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
          body: |
            Maven dependency:

            ```xml
            <dependency>
              <groupId>at.jkvn.dtosimplify</groupId>
              <artifactId>dto-simplify-core</artifactId>
              <version>${{ github.ref_name }}</version>
            </dependency>
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}